### ISSUE TITLE
"RuntimeError: dictionary changed size during iteration" on Bridge Domain

### ISSUE THREAD

**Issue by hpreston** [networktocode/ntc-misc#9]
https://github.com/networktocode/ntc-misc/blob/f3780664c1a1cc0c732a84237452c6d8caed9944/cisco/ansible-aci/02_aci_tenant_network_pb.yml#L23

This maybe a module bug more than a lab bug, but wanted to flag here for reference.  Getting the below when running this playbook using Python 3.6.2 on both Mac and Ubuntu.  Running with Python 2.7.13 works.  

```
TASK [ENSURE TENANT BRIDGE DOMAIN EXISTS] *************************************************************************************************************
task path: /Users/hapresto/coding/ntc-misc/cisco/ansible-aci/02_aci_tenant_network_pb.yml:23
Using module file /Users/hapresto/coding/ntc-misc/cisco/ansible-aci/venv/lib/python3.6/site-packages/ansible/modules/network/aci/aci_bd.py
<sandboxapicdc.cisco.com> ESTABLISH LOCAL CONNECTION FOR USER: hapresto
<sandboxapicdc.cisco.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<sandboxapicdc.cisco.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/hapresto/.ansible/tmp/ansible-tmp-1505916329.651716-16063377934995 `" && echo ansible-tmp-1505916329.651716-16063377934995="` echo /Users/hapresto/.ansible/tmp/ansible-tmp-1505916329.651716-16063377934995 `" ) && sleep 0'
<sandboxapicdc.cisco.com> PUT /var/folders/dh/t0frtgx514388l6ycj2bl7740000gn/T/tmpfv51fh1m TO /Users/hapresto/.ansible/tmp/ansible-tmp-1505916329.651716-16063377934995/aci_bd.py
<sandboxapicdc.cisco.com> EXEC /bin/sh -c 'chmod u+x /Users/hapresto/.ansible/tmp/ansible-tmp-1505916329.651716-16063377934995/ /Users/hapresto/.ansible/tmp/ansible-tmp-1505916329.651716-16063377934995/aci_bd.py && sleep 0'
<sandboxapicdc.cisco.com> EXEC /bin/sh -c '/usr/bin/env python /Users/hapresto/.ansible/tmp/ansible-tmp-1505916329.651716-16063377934995/aci_bd.py; rm -rf "/Users/hapresto/.ansible/tmp/ansible-tmp-1505916329.651716-16063377934995/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/dh/t0frtgx514388l6ycj2bl7740000gn/T/ansible_3iknkomf/ansible_module_aci_bd.py", line 324, in <module>
    main()
  File "/var/folders/dh/t0frtgx514388l6ycj2bl7740000gn/T/ansible_3iknkomf/ansible_module_aci_bd.py", line 307, in main
    {'fvRsBdToEpRet': {'attributes': {'resolveAct': endpoint_retention_action, 'tnFvEpRetPolName': endpoint_retention_policy}}},
  File "/var/folders/dh/t0frtgx514388l6ycj2bl7740000gn/T/ansible_3iknkomf/ansible_modlib.zip/ansible/module_utils/aci.py", line 721, in payload
RuntimeError: dictionary changed size during iteration

fatal: [sandboxapicdc.cisco.com]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/dh/t0frtgx514388l6ycj2bl7740000gn/T/ansible_3iknkomf/ansible_module_aci_bd.py\", line 324, in <module>\n    main()\n  File \"/var/folders/dh/t0frtgx514388l6ycj2bl7740000gn/T/ansible_3iknkomf/ansible_module_aci_bd.py\", line 307, in main\n    {'fvRsBdToEpRet': {'attributes': {'resolveAct': endpoint_retention_action, 'tnFvEpRetPolName': endpoint_retention_policy}}},\n  File \"/var/folders/dh/t0frtgx514388l6ycj2bl7740000gn/T/ansible_3iknkomf/ansible_modlib.zip/ansible/module_utils/aci.py\", line 721, in payload\nRuntimeError: dictionary changed size during iteration\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
	to retry, use: --limit @/Users/hapresto/coding/ntc-misc/cisco/ansible-aci/02_aci_tenant_network_pb.retry
```

**Comment by jmcgill298** [comment]
Will look into this as a aci module issue
